localega:
  token:
  # Username to identify the user in CentralEGA
  user: dummy
  # User secret private RSA key.
  user_key: /config/dummy.key
  # Public key file to encrypt file.
  encrypt_key_public: /config/key.1.pub
  # Private key file to encrypt file.
  encrypt_key_private: /config/key.1.sec
  # Private key password.
  encrypt_key_pass:
  # Inbox address, or service name and port
  tls_cert_tester: /config/tester.ca.crt
  tls_key_tester: /config/tester.ca.key
  tls_ca_root_file: /config/root.ca.crt
  inbox_address: localega-inbox
  inbox_port: 2222
  data_storage_type: "S3Storage" # S3Storage or FileStorage
  # S3 address, or service name, should include port number
  # if s3_address includes `http` it will be removed
  s3_ssl: false
  s3_address:
  s3_access:
  s3_secret:
  s3_region: lega
  s3_bucket: lega
  # CentralEGA Message Broker address
  cm_ssl: false
  cm_address:
  cm_port: 5672
  # CentralEGA Message Broker Country specific details
  cm_user:
  cm_vhost:
  cm_pass:
  # RES address or service name and port
  res_address: localega-res
  res_port: 9090
  # DataEdge address or service name and port
  dataedge_address: localega-dataedge
  dataedge_port: 9059
  # DB address, port will be assumed 5432
  db_ssl: false
  db_address: localega-db
  db_in_user: lega_in
  db_out_user: lega_out
  db_name: lega
  db_in_pass:
  db_out_pass:
