localega:
  token:
  # Username to identify the user in CentralEGA
  user: dummy
  # User secret private RSA key.
  user_key: /config/dummy.key
  # Public key file to encrypt file.
  # This is also the recipient public key
  encrypt_key_public: /config/key.1.pub
  # Private key file to encrypt file.
  encrypt_key_private: /config/key.1.sec
  # Private key password.
  encrypt_key_pass:
  # Inbox address, or service name and port
  tls_cert_tester: /config/tester.ca.crt
  tls_key_tester: /config/tester.ca.key
  tls_ca_root_file: /config/root.ca.crt
  # If inbox_s3 set to true it will ignore
  # sftp inbox parameters
  inbox_s3: false
  inbox_s3_address: localega-s3-inbox
  inbox_s3_access:
  inbox_s3_secret:
  inbox_s3_region: lega
  inbox_s3_ssl: false
  # if the S3 Inbox is public set this below true
  inbox_s3_public: false
  # Parameters for SFTP based inbox
  inbox_address: localega-inbox
  inbox_port: 2222
  data_storage_type: "S3Storage" # S3Storage or FileStorage

  # S3 Archive address, or service name, should include port number
  # if s3_address includes `http` it will be removed
  s3_ssl: false
  # if the S3 Archive is public set this below true
  s3_public: false
  s3_address:
  s3_access:
  s3_secret:
  s3_region: lega
  s3_bucket: lega
  # CentralEGA Message Broker address
  cm_ssl: false
  cm_address:
  cm_port: 5672
  # CentralEGA Message Broker Country specific details
  cm_user:
  cm_vhost:
  cm_pass:
  # DOA address or service name and port
  doa_address: localega-doa
  doa_port: 8080
  # DB address, port will be assumed 5432
  db_ssl: false
  db_address: localega-db
  db_in_user: lega_in
  db_out_user: lega_out
  db_name: lega
  db_in_pass:
  db_out_pass:
